---
homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/versions
  - homebrew/php

homebrew_packages:
  - ansible
  - ansible-lint
  - awscli
  - composer
  - dockutil
  - entr
  - fish
  - git
  - go
  - graphviz
  - httpie
  - hub
  - kubernetes-cli
  - kubernetes-helm
  - mackup
  - mas
  - mkdocs
  - mycli
  - mysql
  - node
  - openshift-cli
  - php71
  - phploc
  - php-code-sniffer
  - php-cs-fixer
  - postgresql
  - pre-commit
  - protobuf
  - rbenv
  - ruby
  - ruby-build
  - rust
  - ssh-copy-id
  - stern
  - terraform
  - tmux
  - tree
  - watchman

homebrew_apps:
  - 1password
  - ableton-live-suite
  - adobe-photoshop-cc
  - alfred
  - angry-ip-scanner
  - appcode
  - atom
  - battle-net
  - cycling74-max
  - daisydisk
  - dash
  - discord
  - docker
  - dropbox
  - fantastical
  - filebot
  - firefox
  - flux
  - google-chrome
  - google-chrome-canary
  - handbrake
  - intellij-idea
  - iterm2
  - karabiner-elements
  - keepingyouawake
  - keybase
  - little-snitch
  - launchrocket
  - livereload
  - micro-snitch
  - microsoft-office
  - minikube
  - minishift
  - moom
  - mou
  - nylas-n1
  - nzbvortex
  - obs
  - openemu
  - origin
  - phpstorm
  - postman
  - renamer
  - sequel-pro
  - skype
  - slack
  - spotify
  - steam
  - the-unarchiver
  - tower
  - transmission
  - transmit
  - unity
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - vmware-fusion
  - webstorm

mas_signin_dialog: yes
mas_installed_apps:
  - { id: 668208984, name: "GIPHY CAPTURE" }
  - { id: 407963104, name: "Pixelmator" }
  - { id: 525180431, name: "Pixen" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409183694, name: "Keynote" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 408981434, name: "iMovie" }
  - { id: 497799835, name: "Xcode" }

npm_pakages:
  - bower
  - ember-cli
  - grunt-cli
  - gulp-cli
