---
- name: Configure Homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Install Homebrew applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_apps }}"
